#!/bin/bash

#@Author: Luis Eduardo Contini Passoni

echo ""

# COLOR FOR THE LOGOS

BLUE_LIGHT="\033[1;36m"
RESET="\033[0m" #WHITE
RED="\033[1;31m"
ORANGE="\033[38;5;208m"
LIGHT_GREEN="\033[1;92m"
BLUE="\033[1;34m"
PURPLE="\033[1;35m"
GREEN="\033[32m"

#________________________________

if [ -f /etc/os-release ]; then
	. /etc/os-release
fi

#----------------------------------

# LOGOS TEST 

if [ -z "$2" ]; then
  :
else
    ID="$2"
fi

#----------------------------------

case $ID in

	arch)
echo -e "${BLUE_LIGHT}$(cat /usr/local/share/ezfetch/logos/arch.txt) ${RESET}"
COR=${BLUE_LIGHT}
		;;
	debian)
echo -e "${RED}$(cat /usr/local/share/ezfetch/logos/debian.txt) ${RESET}"
COR=${RED}
		;;
	ubuntu)
echo -e "${ORANGE}$(cat /usr/local/share/ezfetch/logos/ubuntu.txt) ${RESET}"
COR=${ORANGE}
		;;
	linuxmint)
echo -e "${LIGHT_GREEN}$(cat /usr/local/share/ezfetch/logos/mint.txt) ${RESET}"
COR=${LIGHT_GREEN}
		;;
	fedora)
echo -e "${BLUE}$(cat /usr/local/share/ezfetch/logos/fedora.txt) ${RESET}"
COR=${BLUE}
		;;
	rhel)
echo -e "${RED}$(cat /usr/local/share/ezfetch/logos/rhel.txt) ${RESET}"
COR=${RED}
		;;
	centos)
echo -e "${PURPLE}$(cat /usr/local/share/ezfetch/logos/centos.txt) ${RESET}"
COR=${PURPLE}
		;;
	gentoo)
echo -e "${PURPLE}$(cat /usr/local/share/ezfetch/logos/gentoo.txt) ${RESET}"
COR=${PURPLE}
		;;
	manjaro)
echo -e "${GREEN}$(cat /usr/local/share/ezfetch/logos/manjaro.txt) ${RESET}"
COR=${GREEN}
		;;	
  opensuse)
echo -e "${GREEN}$(cat /usr/local/share/ezfetch/logos/opensuse.txt) ${RESET}"
COR=${GREEN}
		;;
  popos)
echo -e "${GREEN}$(cat /usr/local/share/ezfetch/logos/popos.txt) ${RESET}"
COR=${GREEN}
		;;

esac

MANAGER_NOFORM=$(command -v pacman apt dpkg-query yay yum dnf zypper kiss emerge cpm flatpak brew pkg)
MANAGER=$(basename "$MANAGER_NOFORM")

case $MANAGER in
  apt) PACOTES=$(apt list --installed | wc -l) ;;
	dpkg-query) PACOTES=$(dpkg -l | wc -l) ;;
	pacman) PACOTES=$(pacman -Q | wc -l) ;;
	yay) PACOTES=$(yay -Q | wc -l) ;;
	yum) PACOTES=$(yum list installed | wc -l) ;;
	dnf) PACOTES=$(dnf list installed | wc -l) ;;
	zypper) PACOTES=$(zypper se | wc -l) ;;
	kiss) PACOTES=$(kiss list | wc -l) ;;
	emerge) PACOTES=$(qlist -I | wc -l) ;;
	cpm) PACOTES=$(cpm C) ;;

esac
KERNEL_VERSION=$(uname -r)
UPTIME=$(uptime -p)
USER_NAME=$(whoami)
HOSTNAME=$(cat /etc/hostname)
# Uppercase the first letter of the shell name
SHELL_NAME=$(basename $SHELL | awk '{print toupper(substr($0,1,1)) tolower(substr($0,2))}')
# Formated terminal name
TERM_NAME=$(echo $TERM | awk -F'-' '{print $2}')

echo ""
echo "$USER_NAME@$HOSTNAME"
echo -e "${COR}----------${RESET}o${COR}-----------${RESET}"
echo "OS: $PRETTY_NAME"
echo "Kernel version: $KERNEL_VERSION"
echo "Uptime: $UPTIME"
echo "Packages: $PACOTES"
echo "Shell: $SHELL_NAME"
echo "Terminal: $TERM_NAME"

#If the editor variable is null, prints nothing, if its declared print the name with first letter capitalized. 
EDITOR_NAME=${VISUAL:-"$EDITOR"}

if [ -z "$EDITOR_NAME" ]; then
  :
else
EDITOR_NAME_CAPITALIZED=$(echo "$EDITOR_NAME" | awk '{print toupper(substr($0,1,1)) substr($0,2)}')
  echo "Editor: $EDITOR_NAME_CAPITALIZED"
fi

# Color pallet printing

if [ -z "$1" ]; then
  :
elif [ "$1" == "-c" ];then
    echo ""
for i in {0..7}; do
    echo -e -n "\033[48;5;${i}m  \033[0m"  # Imprime o quadrado de cor
    if (( (i + 1) % 8 == 0 )); then
        echo  # Quebra de linha a cada 8 cores
    fi
done

echo

fi

